### ISSUE TITLE
pygame.error

### ISSUE THREAD

**Issue by drdoof2019** [batuhanerenler/JARVIS-OpenAI-Voice-Assistant#1]
Yazıyı ses'e çevirme noktasında aşağıdaki hatayı veriyor.
```
You: Merhaba benim adım Hasan senin adın ne
AI: Merhaba Beyefendi, benim adım Jarvis. Nasıl yardımcı olabilirim?
Traceback (most recent call last):
  File "C:\Users\user\Desktop\pitonjs\JARVIS-OpenAI-Voice-Assistant\jarvisturkish.py", line 112, in <module>
    main()
  File "C:\Users\user\Desktop\pitonjs\JARVIS-OpenAI-Voice-Assistant\jarvisturkish.py", line 109, in main
    online_tts(response)
  File "C:\Users\user\Desktop\pitonjs\JARVIS-OpenAI-Voice-Assistant\jarvisturkish.py", line 45, in online_tts
    sound = pygame.mixer.Sound(output_file.name)
pygame.error: Unable to open file 'C:\\Users\\user\\AppData\\Local\\Temp\\tmpcn7vnw8y'
```

**Comment by batuhanerenler** [comment]
def online_tts(text, lang="tr", speed=1.0):
    output_folder = os.path.expanduser("~/JarvisOutput")
    os.makedirs(output_folder, exist_ok=True)

    # Create a unique file name for the temporary file
    unique_filename = f"{uuid.uuid4()}.wav"
    output_file_path = os.path.join(output_folder, unique_filename)

    tts = gtts.gTTS(text, lang=lang, slow=False)
    tts.save(output_file_path)

    pygame.init()
    pygame.mixer.init()

    # Load the sound file into a Sound object
    sound = pygame.mixer.Sound(output_file_path)

    # Set the playback speed
    sound.set_volume(1.0 / speed)

    # Play the sound with speed adjustment
    channel = sound.play()
    if channel is not None:
        channel.set_endevent(pygame.USEREVENT)
        is_playing = True
        while is_playing:
            for event in pygame.event.get():
                if event.type == pygame.USEREVENT:
                    is_playing = False
                    break
            pygame.time.Clock().tick(10)

    # Unload the music file and give the system a moment to release the file
    pygame.mixer.quit()
    pygame.time.wait(500)

    # Delete the temporary file manually
    os.remove(output_file_path)


NamedTemproryFile kütüphanesi sorunsuz bir şekilde çalışıyordu bende. Lütfen fonksiyonu bu şekilde güncelleyin. Dosya konumunu özgün biçimde ayarlayacak şekilde kodu güncelledim sizin için. Bir deneyin olmazsa bir daha bakarız, kolay gelsin:)

**Comment by drdoof2019** [comment]
Merhaba
`pygame.error: Unable to open file 'C:\\Users\\user/JarvisOutput\\fdc56507-049b-4b73-a9ca-0181ecdd6e0c.wav'`
Hala hata alıyorum. Kendim kodları şu şekilde düzenledim;
```
  os.environ["TMPDIR"] = os.getcwd() + r"\JS"
  with NamedTemporaryFile(delete=True) as output_file:
      tts = gtts.gTTS(text, lang=lang, slow=False)
      tts.save(output_file.name)
      # os.system("output_file.mp3")

  pygame.init()
  pygame.mixer.init()

  # Load the sound file into a Sound object
  sound = pygame.mixer.Sound(output_file.name)

  # Set the playback speed
  sound.set_volume(1.0 / speed)

  # Play the sound with speed adjustment
  channel = sound.play()
  if channel is not None:
      channel.set_endevent(pygame.USEREVENT)
      is_playing = True
      while is_playing:
          for event in pygame.event.get():
              if event.type == pygame.USEREVENT:
                  is_playing = False
                  break
          pygame.time.Clock().tick(10)

  # Unload the music file and give the system a moment to release the file
  pygame.mixer.quit()
  pygame.time.wait(500)

    # Delete the temporary file manually
    os.remove(output_file.name)
```
Ancak benim versiyonda da aşağıdaki hatayı henüz çözemedim
`PermissionError: [Errno 13] Permission denied: 'C:\\Users\\user\\Desktop\\pitonjs\\jar\\JS\\tmp0_e5ci5h'`

**Comment by batuhanerenler** [comment]
Admin olarak cmd çalışıtırıp komutla çalıştırın hocam app'i büyük ihtimalle çözülecektir. 2-3 arkadaşıma da söyledim sorun olmadan çalıştırdılar lokallerinde.

**Comment by drdoof2019** [comment]
> Admin olarak cmd çalışıtırıp komutla çalıştırın hocam app'i büyük ihtimalle çözülecektir. 2-3 arkadaşıma da söyledim sorun olmadan çalıştırdılar lokallerinde.

Denedim ama olmuyor malesef :)

**Comment by drdoof2019** [comment]
Evvet sorun çözüldü :)
```
import pyttsx3
    # Initialize the pyttsx3 engine
    engine = pyttsx3.init()

    # Set the voice to Turkish
    engine.setProperty('voice', lang)

    # Convert text to speech
    engine.say(text)

    # Play the speech
    engine.runAndWait()
```
bu arkadaşta aynı işlevi yapabiliyor online tts fonksiyonun içine yazıldığında ancak berbat bir türkçesi var :)
o yüzden playsound üzerinden devam etme kararı aldım ve o kadar da uğraşa gerek yokmuş 

```
# Create a gTTS object and generate speech
    tts = gTTS(text=text, lang=lang, slow=False)
    tts.save('speech.mp3')

    # Play the speech using the playsound library
    playsound('speech.mp3')
```
api limitim dolduğu için kendi ses inputumu ai'in response'si olarak tanımladım yani bi çeşit papağan jarvis oldu ama en azından çalıştırmayı başardım 💯 
Aynı sorunu yaşayan olursa `def online_tts(text, lang='tr', speed=1):` bu arkadaşın içini temizleyip yukarıdaki kodu yazabilir.


Bazen donuyor ama anlaşmaya başlıyoruz :)
![image](https://user-images.githubusercontent.com/50274757/229312025-06b8627d-4810-46b2-a843-cd00452c6007.png)
Kapanma komutlarını biraz genişlettim ve hepsinin başına jarvis koydum. Jarvis ingilizce bir kelime olduğu için türkçe okuyunca da çok saçma olduğu için cervis gibi alternatiflerini de ekledim onu da burda paylaşmış olayım :)

```
quit_list = ["jarvis quit", "jarvis exit", "jarvis bye", "jarvis bay", "jarvis kapan",
                     "jarvis kendini kapat",
                     "carvis quit", "carvis exit", "carvis bye", "carvis bay", "carvis kapan",
                     "carvis kendini kapat",
                     "cervis quit", "cervis exit", "cervis bye", "cervis bay", "cervis kapan",
                     "cervis kendini kapat"]
if user_input.lower() in quit_list:
     break
```
